name: bg3_vfx_helper
description: "BG3 VFX Helper is a tool to help fixing custom head VFX in Baldur's Gate 3."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.3
  window_manager: ^0.5.1
  provider: ^6.1.5+1
  async_locks: ^4.0.2
  xml: ^6.6.1
  path: ^1.9.1
  uuid: ^4.5.2
  bloc: ^9.1.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
